"""Shared constants for file handling and UI."""

UPLOAD_EXTENSIONS = {".csv", ".xlsx", ".xls"}
STREAMLIT_UPLOAD_TYPES = ["csv", "xlsx", "xls"]

# UTF-8 with BOM helps Excel on Windows recognize UTF-8 CSV correctly.
CSV_ENCODING = "utf-8-sig"

# Columns written to the export — matches ``format.xlsx`` header row (122 cols).
# Columns absent from the upload are emitted blank; order is preserved.
OUTPUT_COLUMN_ORDER: tuple[str, ...] = (
    "External ID",
    "_FBM UPC",
    "Vendor Name",
    "Netsuite Style Name",
    "Color Free Form",
    "MPN",
    "Vendor Color Code",
    "SIZE",
    "Season Code",
    "STATUS",
    "MAP RELEASE DATE",
    "AMAZON PRICE",
    "OFF MAP",
    "RETAIL PRICE",
    "MSRP PRICE",
    "AMAZON LINK",
    "SELLER CENTRAL LINK",
    "NETSUITE LINK",
    "MASTER PARENT ASIN",
    "MASTER CHILD ASIN",
    "Parent ASIN 4.30.26",
    "Parent Asin Match 4.30.26",
    "ASIN 4.30.26",
    " Buy Box: Is FBA",
    " Buy Box Seller",
    " Buy Box: Stock",
    " Amazon: Current BUY BOX  Price",
    " Buy Box Eligible Offer Counts: New FBA",
    " Buy Box Eligible Offer Counts: New FBM",
    " Amazon: Stock",
    " Bought in past month",
    " ACTIVE/INACTIVE",
    "FBM QTY",
    "FBM PRICE",
    " CURRENT SHIP TEMP (MIG-STANDARD, SHIP-ADD 9.99)",
    " ACTIVE/INACTIVE.1",
    "AMZ PRICE",
    "AMZ TAG",
    "repricing_enabled FBA ",
    "repricing_enabled MFN ",
    "repricing_enabled FBM ",
    "offer_position FBA ",
    "offer_position MFN ",
    "offer_position FBM ",
    "min_price FBA ",
    "min_price MFN ",
    "min_price FBM ",
    "max_price FBA ",
    "max_price MFN ",
    "max_price FBM ",
    "current_price FBA ",
    "current_price MFN ",
    "current_price FBM ",
    "current_shipping FBA ",
    "current_shipping MFN ",
    "current_shipping FBM ",
    "featured FBA ",
    "featured MFN ",
    "featured FBM ",
    "is_buy_box_winner FBA ",
    "is_buy_box_winner MFN ",
    "is_buy_box_winner FBM ",
    "has_buy_box FBA ",
    "has_buy_box MFN ",
    "has_buy_box FBM ",
    "STORE SALES 4.20-4.26.26",
    "AMZ SALES 4.19-4.25.26",
    " Total Days of Supply (including units from open shipments) ",
    " Recommended replenishment qty",
    "STORE INV ",
    "STORE ON ORDER ",
    "STORE MINS ",
    "FC INV ",
    "FC ON ORDER ",
    " inv-age-0-to-90-days",
    " inv-age-91-to-180-days",
    " inv-age-181-to-270-days",
    " inv-age-271-to-365-days",
    " inv-age-365-plus-days",
    "Recomened Removel+",
    "12.15 afn-total-quantity",
    "afn-fulfillable-quantity",
    "afn-unsellable-quantity",
    "afn-reserved-quantity",
    "afn-inbound-working-quantity",
    "afn-inbound-shipped-quantity",
    "afn-inbound-receiving-quantity",
    "afn-researching-quantity (inbound inv.not avail. for sale)",
    " afn-total-quantity",
    " afn-fulfillable-quantity",
    " afn-unsellable-quantity",
    " afn-reserved-quantity",
    "Reserved Customer Order",
    " afn-inbound-working-quantity",
    " afn-inbound-shipped-quantity",
    " afn-inbound-receiving-quantity",
    " afn-researching-quantity (inbound inv.not avail. for sale)",
    "UPC Code",
    "Price Level",
    "Unit Price",
    "Current Price",
    "Average Cost",
    "Purchase Price",
    "MSRP",
    "Shipping Override",
    "Location Reorder Point",
    "Last Markdown Date",
    "ITEM SID",
    "Internal ID",
    "EXCLUDE FROM AMAZON",
    "EXCLUDE FROM EBAY",
    "EXCLUDE FROM MSW.COM",
    "Last Purchase Price",
    "Amazon Minimum Price",
    "AMAZON MAX PRICE",
    "FBA STORAGE TYPE",
    "Parent",
    "SEND TO FBA",
    "FBA ONLY",
    "MAP RELEASE DATE.1",
    "ASIN",
    "AMZ SOURCING COST",
)
